import { useState } from 'react';
import { motion } from 'motion/react';
import { 
  ShieldCheck, 
  AlertOctagon, 
  AlertTriangle, 
  CheckCircle2, 
  Copy, 
  Check, 
  ArrowLeft, 
  Printer, 
  ArrowUpRight
} from 'lucide-react';
import { AnalysisResult } from '../types';
import { SentimentCard } from './SentimentCard';
import { TrustedSourcesCard } from './TrustedSourcesCard';
import { ClaimsList } from './ClaimsList';
import { LinguisticFlagsCard } from './LinguisticFlagsCard';

interface AnalysisResultViewProps {
  result: AnalysisResult;
  onAnalyzeAnother: () => void;
}

export function AnalysisResultView({ result, onAnalyzeAnother }: AnalysisResultViewProps) {
  const [copied, setCopied] = useState(false);

  // Verdict style mapping
  const getVerdictDetails = (verdict: string) => {
    switch (verdict) {
      case 'VERIFIED_TRUE':
        return {
          title: 'Verified Authentic Reporting',
          desc: 'Claims are supported by primary documentation, accredited news wires, and empirical citations.',
          badgeBg: 'bg-emerald-50 text-emerald-800 border-emerald-200',
          scoreColor: 'text-emerald-700',
          barColor: 'bg-emerald-600',
          icon: <ShieldCheck className="w-5 h-5 text-emerald-700" />
        };
      case 'LIKELY_AUTHENTIC':
        return {
          title: 'Likely Authentic Context',
          desc: 'High factual consistency with established sources, with standard journalistic commentary.',
          badgeBg: 'bg-teal-50 text-teal-800 border-teal-200',
          scoreColor: 'text-teal-700',
          barColor: 'bg-teal-600',
          icon: <CheckCircle2 className="w-5 h-5 text-teal-700" />
        };
      case 'MIXED_OR_MISLEADING':
        return {
          title: 'Mixed or Misleading Elements',
          desc: 'True facts intermingled with selective omissions, outdated events, or sensationalist exaggeration.',
          badgeBg: 'bg-amber-50 text-amber-800 border-amber-200',
          scoreColor: 'text-amber-700',
          barColor: 'bg-amber-500',
          icon: <AlertTriangle className="w-5 h-5 text-amber-700" />
        };
      case 'QUESTIONABLE':
        return {
          title: 'Low Credibility / Questionable',
          desc: 'Substantial lack of corroborating evidence, reliance on rumors, or partisan distortion.',
          badgeBg: 'bg-orange-50 text-orange-800 border-orange-200',
          scoreColor: 'text-orange-700',
          barColor: 'bg-orange-500',
          icon: <AlertOctagon className="w-5 h-5 text-orange-700" />
        };
      case 'CONFIRMED_FALSE':
      default:
        return {
          title: 'Fabricated or Disinformation Hoax',
          desc: 'Wholly fabricated claims, debunked theories, or manipulative rhetoric contradicted by reality.',
          badgeBg: 'bg-rose-50 text-rose-800 border-rose-200',
          scoreColor: 'text-rose-700',
          barColor: 'bg-rose-600',
          icon: <AlertOctagon className="w-5 h-5 text-rose-700" />
        };
    }
  };

  const getRiskBadge = (risk: string) => {
    switch (risk) {
      case 'CRITICAL':
        return 'bg-rose-50 text-rose-800 border-rose-200';
      case 'HIGH':
        return 'bg-orange-50 text-orange-800 border-orange-200';
      case 'MODERATE':
        return 'bg-amber-50 text-amber-800 border-amber-200';
      case 'LOW':
      default:
        return 'bg-emerald-50 text-emerald-800 border-emerald-200';
    }
  };

  const verdictMeta = getVerdictDetails(result.verdict);

  const handleCopyReport = async () => {
    const reportText = `[VERITAS EDITORIAL AUDIT REPORT]
Article Title: ${result.articleTitle}
Credibility Score: ${result.credibilityScore} / 100 (${result.verdict})
Risk Level: ${result.riskLevel}
Sentiment Polarity: ${result.sentiment.score > 0 ? `+${result.sentiment.score}` : result.sentiment.score} (${result.sentiment.label})
Sensationalism Index: ${result.sentiment.sensationalismScore}% | Subjectivity: ${result.sentiment.subjectivityScore}%
Dominant Tone: ${result.sentiment.dominantTone}

Reasoning:
${result.verdictReasoning}

Key Fact Claims Tested (${result.claims.length}):
${result.claims.map(c => `- [${c.verdict}] ${c.claim}: ${c.explanation}`).join('\n')}

Trusted Sources Cited (${result.trustedCitations.length}):
${result.trustedCitations.map(cit => `- ${cit.publisher} (${cit.title}): ${cit.url}`).join('\n')}

Generated by Veritas AI Editorial Suite`;

    try {
      await navigator.clipboard.writeText(reportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (err) {
      console.error('Failed to copy report:', err);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
      id="analysis-report-root" 
      className="space-y-6"
    >
      {/* Top Action Toolbar in Superhuman style */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white p-4 rounded-[16px] border border-[#e3e3e2] print:hidden">
        <button
          type="button"
          id="btn-back-to-input"
          onClick={onAnalyzeAnother}
          className="inline-flex items-center gap-2 text-xs font-[500] text-[#292827] hover:text-[#714cb6] transition-colors py-1.5 px-3 rounded-[8px] hover:bg-[#f2f0eb] cursor-pointer"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Inspect Another Article</span>
        </button>

        <div className="flex items-center gap-2">
          <button
            type="button"
            id="btn-copy-report"
            onClick={handleCopyReport}
            className="inline-flex items-center gap-1.5 text-xs font-[460] text-[#292827] hover:text-[#421d24] bg-[#f2f0eb] hover:bg-[#e3e3e2] border border-[#e3e3e2] px-3.5 py-1.5 rounded-[8px] transition-colors cursor-pointer"
            title="Copy formatted text report"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-700" /> : <Copy className="w-3.5 h-3.5 text-[#666666]" />}
            <span>{copied ? 'Summary Copied' : 'Copy Summary'}</span>
          </button>

          <button
            type="button"
            id="btn-print-report"
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 text-xs font-[500] text-[#292827] bg-[#d4c7ff] hover:bg-[#c7b6ff] border border-[#292827] px-4 py-1.5 rounded-[8px] transition-all cursor-pointer"
            title="Print or Save PDF"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Export PDF &rarr;</span>
          </button>
        </div>
      </div>

      {/* Superhuman Editorial Score & Synthesis Banner: Dual Floating Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Card: Score & Index */}
        <div className="lg:col-span-5 bg-white p-6 sm:p-8 border border-[#e3e3e2] rounded-[16px] flex flex-col justify-between">
          <div>
            <div className="text-xs font-[500] uppercase tracking-wider text-[#666666] mb-4">
              Credibility Index
            </div>
            
            <div className="flex items-baseline gap-2 mb-3">
              <span className="text-6xl sm:text-7xl font-[460] text-[#292827] tracking-tight">
                {result.credibilityScore}
              </span>
              <span className="text-2xl font-[460] text-[#666666]">
                / 100
              </span>
            </div>

            {/* Hairline geometric meter */}
            <div className="mt-4 h-2 w-full bg-[#f2f0eb] rounded-full overflow-hidden">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${result.credibilityScore}%` }}
                transition={{ duration: 0.8, ease: "easeOut" }}
                className={`h-full ${verdictMeta.barColor}`}
              />
            </div>
          </div>

          <div className="mt-8 pt-5 border-t border-[#e3e3e2]">
            <div className="flex items-center gap-2 mb-2">
              <span className={`px-2.5 py-0.5 rounded-full text-xs font-[500] border ${verdictMeta.badgeBg}`}>
                {result.verdict.replace(/_/g, ' ')}
              </span>
              <span className="text-xs text-[#666666] font-[460]">
                Algorithmic Audit
              </span>
            </div>
            <p className="text-xs sm:text-sm text-[#666666] leading-relaxed font-[460]">
              {verdictMeta.desc}
            </p>
          </div>
        </div>

        {/* Right Card: Editorial Reasoning & Context */}
        <div className="lg:col-span-7 bg-white p-6 sm:p-8 border border-[#e3e3e2] rounded-[16px] flex flex-col justify-between">
          <div>
            <div className="flex flex-wrap items-center justify-between gap-2 mb-3">
              <span className="text-xs font-[500] uppercase tracking-wider text-[#714cb6]">
                Editorial Synthesis
              </span>
              <span className={`px-2.5 py-0.5 rounded-full text-xs font-[500] border ${getRiskBadge(result.riskLevel)}`}>
                {result.riskLevel} Misinformation Risk
              </span>
            </div>

            <h2 className="text-2xl sm:text-3xl font-[460] text-[#292827] tracking-[-0.022em] mb-3">
              {verdictMeta.title}
            </h2>

            <p className="text-sm sm:text-base text-[#292827] leading-relaxed font-[460] mb-4">
              {result.verdictReasoning}
            </p>
          </div>

          <div className="pt-4 border-t border-[#e3e3e2] flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
            <div className="text-[#666666] truncate max-w-md font-[460]">
              <span className="text-[#292827] font-[500]">Subject: </span>
              <span className="italic">"{result.articleTitle}"</span>
            </div>
            <span className="text-[#666666] font-mono text-[11px] shrink-0">
              Audit recorded {new Date(result.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
            </span>
          </div>
        </div>
      </div>

      {/* Grid: Sentiment Analysis Card */}
      <SentimentCard 
        sentiment={result.sentiment} 
        factVsOpinion={result.factVsOpinionRatio} 
      />

      {/* Grid: Trusted Sources Cited Card */}
      <TrustedSourcesCard 
        citations={result.trustedCitations} 
        searchQueries={result.searchGroundingQueriesUsed}
      />

      {/* Claims Fact-Check Dissection */}
      <ClaimsList claims={result.claims} />

      {/* Linguistic Indicators & Actionable Checklist */}
      <LinguisticFlagsCard 
        flags={result.linguisticFlags} 
        recommendations={result.recommendations} 
      />
    </motion.div>
  );
}
